#Kabanero! on activate substitute Digest for text '@Digest@'
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: image-retag-pl-@Digest@
spec:
  resources:
    - name: docker-src-image
      type: image
    - name: docker-dest-image
      type: image
  tasks:
    - name: image-retag-task
      taskRef:
        name: image-retag-task-@Digest@
      resources:
        inputs:
        - name: docker-src-image
          resource: docker-src-image
        - name: docker-dest-image
          resource: docker-dest-image
        outputs:
        - name: docker-dest-image
          resource: docker-dest-image
