apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: <stack-name>-manual-pipeline-run
spec:
  params:
  - name: event-type
    value: push
  - name: event-ref
    value: refs/heads/master
  serviceAccountName: kabanero-pipeline
  timeout: "1h0m0s"
  pipelineRef:
    name: <stack-name>-build-deploy-pl
  resources:
    - name: git-source
      resourceRef:
        name: git-source
    - name: docker-image
      resourceRef:
        name: docker-image
