#Kabanero! on activate substitute StackId for text 'StackId'
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: StackId-build-pl
spec:
  resources:
    - name: git-source
      type: git
    - name: docker-image
      type: image
  tasks:
    - name: validate-stack-task
      taskRef:
        name: StackId-validate-stack-task
      resources:
        inputs:
        - name: git-source
          resource: git-source
    - name: build-task
      taskRef:
        name: StackId-build-task
      runAfter: [validate-stack-task]
      resources:
        inputs:
        - name: git-source
          resource: git-source
        outputs:
        - name: docker-image
          resource: docker-image
